CREATE TABLE Innovator
(
  InnovatorID INT NOT NULL AUTO_INCREMENT,
  InnovatorName VARCHAR(30) NOT NULL,  
  InnovatorEmail VARCHAR(30) NOT NULL,
  PRIMARY KEY (InnovatorID)
);

CREATE TABLE IH_Support
(
  IHSID INT NOT NULL AUTO_INCREMENT,
  IHSName VARCHAR(30) NOT NULL,
  IHSEmail VARCHAR(30) NOT NULL,
  IHSPassword VARCHAR(30) NOT NULL,
  PRIMARY KEY (IHSID)
);

CREATE TABLE Company
(
  CompanyID INT NOT NULL AUTO_INCREMENT,  
  CompanyName VARCHAR(30) NOT NULL,
  CompanyURL VARCHAR(30) NOT NULL,
  PRIMARY KEY (CompanyID)
);

CREATE TABLE Admin
(
  AdminID INT NOT NULL AUTO_INCREMENT,
  AdminName VARCHAR(30) NOT NULL,
  AdminPassword VARCHAR(30) NOT NULL,
  AdminEmail VARCHAR(30) NOT NULL,
  CompanyID INT NOT NULL,
  PRIMARY KEY (AdminID),
  FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
);

CREATE TABLE Idea
(
  IdeaID INT NOT NULL AUTO_INCREMENT,
  IdeaSubmission VARCHAR(400) NOT NULL,
  IdeaDT DATETIME NOT NULL,
  InnovatorID INT NOT NULL,
  CompanyID INT NOT NULL,
  PRIMARY KEY (IdeaID),
  FOREIGN KEY (InnovatorID) REFERENCES Innovator(InnovatorID),
  FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
);